// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/components/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // 1. Title Template: Adapts to Legal or IT service names automatically
  title: {
    default: "TechVisionNext | Legal Consulting & IT Solutions",
    template: "%s | TechVisionNext",
  },
  
  // 2. Multi-niche Description
  description: "Your comprehensive partner for legal compliance and technical excellence. We offer GST registration, Company Incorporation, and Tax services alongside specialized IT solutions and software development.",
  
  // 3. Categorized Keywords
  keywords: [
    "Legal Services India", "GST Registration", "Company Incorporation", 
    "IT Consulting", "Software Development", "Tax Advisory", 
    "Trademark Filing", "Digital Transformation", "Business Compliance"
  ],

  // 4. Open Graph (Social Media)
  openGraph: {
    title: "TechVisionNext - Legal Clarity, Technical Innovation",
    description: "Bridging the gap between legal compliance and IT excellence for modern businesses.",
    url: "https://techvisionnext.com",
    siteName: "TechVisionNext",
    images: [
      {
        url: "/og-main-banner.jpg", // A professional banner representing both tech and law
        width: 1200,
        height: 630,
        alt: "TechVisionNext Legal and IT Services",
      },
    ],
    locale: "en_IN",
    type: "website",
  },

  // 5. Additional SEO Essentials
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  // 6. Mobile & Theme Settings
  viewport: "width=device-width, initial-scale=1",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-orange-100`}
      >
        <WhatsAppButton/>
        {children}
      </body>
    </html>
  );
}